const state={tone:'duhovit',currentReplies:[],mediaLink:''};
const $=s=>document.querySelector(s);const message=$('#message'),results=$('#results'),template=$('#replyTemplate');
const dictionaries={fudbal:['fudbal','gol','golman','liga','kup','derbi','penal','ofsajd','marakana','superliga','liga šampiona','teren'],košarka:['košarka','basket','evroliga','aba','trojka','koš','faul','centar','plej','parket','arena'],evropa:['evropa','evroliga','liga šampiona','uefa','final four'],titule:['titula','titule','šampion','trofej','kup'],sudije:['sudija','sudije','penal','faul','krađa','pokradeni'],rezultat:['pobeda','poraz','izgubili','dobili','rezultat','razbili','petarda'],finansije:['dug','dugovi','pare','budžet','država','sponzor']};
const switchPhrases=['nije bitan fudbal','pričajmo o košarci','pređimo na košarku','a košarka','a fudbal','ma pusti fudbal','ma pusti košarku'];
const countMatches=(t,w)=>w.reduce((n,x)=>n+(t.includes(x)?1:0),0);
function detectSport(text){const v=text.toLowerCase(),f=countMatches(v,dictionaries.fudbal),k=countMatches(v,dictionaries.košarka);if(f&&k)return'oba';if(k>f)return'košarka';if(f>k)return'fudbal';return'nepoznato'}
function sportLabel(s){return({fudbal:'Fudbal',košarka:'Košarka',oba:'Fudbal i košarka',nepoznato:'Nije jasno'})[s]||s}
function detectTopic(text){const v=text.toLowerCase(),scores=Object.entries(dictionaries).filter(([k])=>!['fudbal','košarka'].includes(k)).map(([k,w])=>[k,countMatches(v,w)]).sort((a,b)=>b[1]-a[1]),winner=scores[0];if(!winner||winner[1]===0)return'Opšta prozivka';return({evropa:'Evropa',titule:'Titule i trofeji',sudije:'Sudije',rezultat:'Rezultat',finansije:'Finansije kluba'})[winner[0]]}
function analyzeMessage(text){const v=text.toLowerCase(),detected=detectSport(v),topic=detectTopic(v),changedTopic=switchPhrases.some(p=>v.includes(p))||detected==='oba',mock=countMatches(v,['haha','raspad','smešni','jadni','bruk','blam','razbili']),aggr=countMatches(v,['glup','idiot','mrzim','sramota']),exc=(v.match(/!/g)||[]).length;let tone='Navijačko zadirkivanje';if(aggr)tone='Preterano oštar';else if(mock>1||exc>2)tone='Podsmevanje';else if(v.includes('?'))tone='Provokativno pitanje';let score=Math.max(1,Math.min(10,3+mock+Math.min(exc,2)+(changedTopic?2:0)+Math.min(aggr,2)));let advice=changedTopic?'Menja temu — vrati ga na početno pitanje.':tone==='Preterano oštar'?'Poklopi ga kratko i bez lične uvrede.':'Najbolje prolazi kratka, precizna replika.';return{detected,topic,changedTopic,tone,score,advice}}
function context(){const a=analyzeMessage(message.value.trim()),chosen=$('#sport').value;if(chosen!=='auto')a.detected=chosen;return{myClub:$('#myClub').value,rival:$('#rivalClub').value,friend:$('#friendName').value.trim()||'majstore',incoming:message.value.trim(),persona:$('#persona').value,...a}}
const pools={
 duhovit:ctx=>[`${ctx.friend}, toliko pratiš ${ctx.myClub} da ćemo ti uskoro naplatiti članarinu.`,`Više znaš raspored ${ctx.myClub} nego svog kluba. To više nije rivalstvo, to je fan stranica.`,`Dobra prozivka. Još samo činjenica da se pojavi i kompletna je.`,`Čekaj, navijaš za ${ctx.rival} ili vodiš krizni PR za moj klub?`],
 cinjenice:()=>['Pošalji sezonu, takmičenje i izvor. Bez toga je to samo navijačka priča.','Jedna utakmica nije cela sezona, a jedna sezona nije cela istorija.','Poredi iste periode i ista takmičenja, pa ćemo videti ko šta stvarno ima.','Buka ne menja tabelu, rezultat ni arhivu.'],
 ostar:ctx=>[`Ne brini za ${ctx.myClub}. Objasni prvo zašto ti je moj klub glavna tema posle svake utakmice.`,`Kad ponestanu argumenti, ostanu velika slova, stikeri i promena teme.`,`Može prozivka, ali sledeći put ponesi i dokaz.`,`Najglasniji deo tvoje poruke je baš onaj bez pokrića.`],
 brutalan:ctx=>[`Tvoja poruka ima više samopouzdanja nego sadržaja. U prevodu: buka bez rezultata.`,`Opet pričaš o ${ctx.myClub}. Vaš klub očigledno nije dovoljno zanimljiv ni sopstvenim navijačima.`,`Menjaš temu čim dođemo do činjenica. To nije rasprava, to je bekstvo sa terena.`,`Da ti je argument jak koliko prozivka, ne bi morao da ga ponavljaš pet puta.`,`Ti ne pratiš Partizan — ti dežuraš nad njim. Još malo pa ćeš dobiti smenu u Humskoj.`,`Najveći uspeh ove poruke je što je stigla bez ijednog dokaza.`],
 kulturan:ctx=>[`Čestitam kada je zasluženo, ali ostajem uz ${ctx.myClub} i kada pobedi i kada izgubi.`,`Rivalstvo je dobro dok ostane na šali i tačnim podacima.`,`Možemo da se ne slažemo, ali hajde bez prepravljanja istorije.`,`Poštujem prozivku, samo joj nedostaje malo konteksta.`],
 grupa:ctx=>[`${ctx.friend} je upravo aktivirao rezervnu temu jer glavni argument više nije dostupan.`,`VAR proverava poruku, ali dokaz još nije pronađen.`,`Stručni štab javlja: 5% činjenica, 95% navijačkog samopouzdanja.`,`Nova taktika: tri stikera, dve parole i nijedan izvor.`]
};
function replyPool(ctx){if(ctx.changedTopic)return[`${ctx.friend}, sport se ne menja usred rasprave samo zato što rezultat više ne odgovara.`,'Dobra promena teme, ali prethodno pitanje i dalje čeka odgovor.','Menjaš sport brže nego TV kanal — prvo završi ono što si otvorio.','Kad argument oslabi, odmah se prelazi na drugu disciplinu. Providno.'];return(pools[state.tone]||pools.duhovit)(ctx)}
function persona(text,p){const w={normalan:v=>v,komentator:v=>`Ulazimo u završnicu rasprave! ${v}`,advokat:v=>`Poštovani protivniče, ${v.toLowerCase()} Molim dokaz.`,profesor:v=>`Lekcija dana: ${v}`,trener:v=>`Taktičko uputstvo: ${v}`,novinar:v=>`Iz Viber redakcije: ${v}`};return(w[p]||w.normalan)(text)}
function renderAnalysis(a){$('#analysisPanel').classList.remove('hidden');$('#iqScore').textContent=`${a.score}/10`;$('#topicValue').textContent=a.topic;$('#sportValue').textContent=sportLabel(a.detected);$('#toneValue').textContent=a.tone;$('#switchValue').textContent=a.changedTopic?'Da — beži sa teme':'Nije primećena';$('#analysisAdvice').textContent=a.advice}
function shortenText(t){let x=t.replace(/^Ulazimo u završnicu rasprave!\s*/i,'').replace(/^Poštovani protivniče,\s*/i,'').replace(/^Lekcija dana:\s*/i,'').replace(/^Taktičko uputstvo:\s*/i,'').replace(/^Iz Viber redakcije:\s*/i,'').replace(/\s+Molim dokaz\.?$/i,'').trim();const s=x.match(/[^.!?]+[.!?]?/g)||[x];x=s[0].trim();return x.length>110?`${x.slice(0,107).trim()}…`:x}
function fullShareText(text){return state.mediaLink?`${text}\n\n${state.mediaLink}`:text}
async function copyText(text,button){try{await navigator.clipboard.writeText(text);const old=button.textContent;button.textContent='Kopirano ✓';button.classList.add('copied');setTimeout(()=>{button.textContent=old;button.classList.remove('copied')},1500)}catch{window.prompt('Kopiraj odgovor:',text)}}
async function shareText(text,button){const payload=fullShareText(text);if(navigator.share){try{await navigator.share({text:payload});return}catch(e){if(e&&e.name==='AbortError')return}}await copyText(payload,button);alert('Odgovor i link su kopirani. Otvori Viber i nalepi.')}
function createCard(text,index,best=false){const node=template.content.cloneNode(true),article=node.querySelector('.reply-card'),textEl=node.querySelector('.reply-text'),badge=node.querySelector('.reply-badge'),linkEl=node.querySelector('.attached-link');node.querySelector('.reply-number').textContent=index+1;textEl.textContent=text;badge.textContent=best?'⭐ Najbolji odgovor':'Još jedan predlog';if(best)article.classList.add('best-reply');if(state.mediaLink){linkEl.textContent=`Uz odgovor se deli: ${state.mediaLink}`;linkEl.classList.remove('hidden')}node.querySelector('.share-button').onclick=()=>shareText(textEl.textContent,node.querySelector('.share-button'));node.querySelector('.copy-button').onclick=()=>copyText(fullShareText(textEl.textContent),node.querySelector('.copy-button'));node.querySelector('.shorten-button').onclick=e=>{textEl.textContent=shortenText(textEl.textContent);e.currentTarget.textContent='Skraćeno ✓';e.currentTarget.disabled=true};return node}
function renderReplies(showAll=false){results.innerHTML='';if(!state.currentReplies.length)return;results.appendChild(createCard(state.currentReplies[0],0,true));if(showAll)state.currentReplies.slice(1,4).forEach((t,i)=>results.appendChild(createCard(t,i+1)));else{const b=document.createElement('button');b.className='more-button';b.textContent='⚡ Još 3 odgovora';b.onclick=()=>renderReplies(true);results.appendChild(b)}}
function saveHistory(ctx){const h=JSON.parse(localStorage.getItem('navijacki-history')||'[]');h.unshift({date:new Date().toLocaleString('sr-RS'),friend:ctx.friend,message:ctx.incoming,sport:sportLabel(ctx.detected),topic:ctx.topic});localStorage.setItem('navijacki-history',JSON.stringify(h.slice(0,20)));renderHistory()}
function esc(v){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'})[c])}
function renderHistory(){const h=JSON.parse(localStorage.getItem('navijacki-history')||'[]'),list=$('#historyList');list.innerHTML=h.length?h.slice(0,5).map(x=>`<article class="history-item"><div><strong>${esc(x.friend)}</strong><span>${esc(x.date)}</span></div><p>${esc(x.message)}</p><small>${esc(x.sport)} · ${esc(x.topic)}</small></article>`).join(''):'<p class="empty-history">Još nema sačuvanih rasprava.</p>'}
function generate(){const ctx=context();if(!ctx.incoming){results.innerHTML='<div class="card empty-state">Prvo ubaci njegovu poruku.</div>';message.focus();return}renderAnalysis(ctx);state.currentReplies=replyPool(ctx).map(t=>persona(t,ctx.persona));renderReplies(false);saveHistory(ctx);results.scrollIntoView({behavior:'smooth',block:'start'})}
async function pasteClipboard(){const note=$('#clipboardNote');try{const t=await navigator.clipboard.readText();if(!t.trim()){note.textContent='U clipboardu nema teksta.';return}message.value=t.slice(0,600);message.dispatchEvent(new Event('input'));note.textContent='Poruka je ubačena.'}catch{note.textContent='Ako pristup nije dozvoljen, zadrži prst u polju i izaberi Nalepi.';message.focus()}}
function updateDetected(){const s=$('#sport').value==='auto'?detectSport(message.value):$('#sport').value;$('#detectedSport').textContent=`Sport: ${sportLabel(s)}`}
document.querySelectorAll('.tone').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tone').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.tone=b.dataset.tone});
message.oninput=()=>{$('#charCount').textContent=`${message.value.length}/600`;updateDetected()};
$('#pasteClipboard').onclick=pasteClipboard;$('#analyze').onclick=()=>message.value.trim()&&renderAnalysis(context());$('#generate').onclick=generate;$('#sport').onchange=updateDetected;
$('#useMedia').onclick=()=>{const v=$('#mediaLink').value.trim();if(!/^https?:\/\//i.test(v)){ $('#mediaStatus').textContent='Nalepi pun link koji počinje sa http:// ili https://';return}state.mediaLink=v;localStorage.setItem('navijacki-media-link',v);$('#mediaStatus').textContent='Link će biti dodat uz sledeće deljenje.';if(state.currentReplies.length)renderReplies(true)};
$('#clearMedia').onclick=()=>{state.mediaLink='';$('#mediaLink').value='';localStorage.removeItem('navijacki-media-link');$('#mediaStatus').textContent='Link je uklonjen.';if(state.currentReplies.length)renderReplies(true)};
$('#clearHistory').onclick=()=>{localStorage.removeItem('navijacki-history');renderHistory()};
['myClub','rivalClub','sport','friendName','persona'].forEach(id=>{const el=document.getElementById(id),saved=localStorage.getItem(`navijacki-${id}`);if(saved)el.value=saved;el.onchange=()=>localStorage.setItem(`navijacki-${id}`,el.value)});
state.mediaLink=localStorage.getItem('navijacki-media-link')||'';if(state.mediaLink){$('#mediaLink').value=state.mediaLink;$('#mediaStatus').textContent='Sačuvan link će biti dodat uz odgovor.'}updateDetected();renderHistory();